#!/bin/bash
# Scripts intro

This repository contains some bash scripts that perform 
various tasks.

## Scripts

read.sh prints "ALX DO HARD THINGS" to the output
counter.sh This script counts the number of files from a specified folder and prints the output

